# -*- coding: utf-8 -*-
"""modul

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SdTDGr71TsHiUH9KJTbWphrcSH5FyDwO
"""

class kantin:
  jumlah_menu = 0 
#Method untuk menginisialisasikan hal-hal apa saja yang diperlukan dalam objek
  def __init__(self, kode, menu, harga):
    self.kode = kode
    self.menu = menu
    self.harga = harga
    kantin.jumlah_menu += 1
#Method untuk menampilkan daftar menu
  def tampilkan_profil(self):
    print(self.kode,self.menu,self.harga)

#instance(untuk ini saya langsung taro di percabangannya kak)
menu1 = kantin(1,'\tJus Mangga\t','Rp.9.000')
menu2 = kantin(2,'\tNasi Goreng\t','Rp.12.000')
menu3 = kantin(3,'\tPaket Hemat\t','Rp.18.000')

#Method untuk menampilkan hasil/total yang harus dibayar
def total(harga, jumlah):
  return harga*jumlah